# Site settings
title: T. LEUNG
email: tleung@student.unimelb.edu.au
description: "The goal of this blog is to provide tutorials that can make readers have better understanding about computer system and system security. "
baseurl: ""
url: "http://timothyleung.github.io"

# Build settings
markdown: kramdown
permalink: pretty
